### ISSUE TITLE
False Positive 

### ISSUE THREAD

**Issue by snlamm** [learn-co-curriculum/sql-library-lab#12] opened 2016-04-14 21:25 UTC
In querying.rb, the following code passes the tests:

def select_series_title_with_most_human_characters
  "SELECT series.title 
  FROM series
  JOIN characters
  ON series.id = characters.series_id

  GROUP BY series.title
  ORDER BY SUM(characters.species) DESC
  LIMIT 1"
end

This, however, totals all the characters without totaling all the human characters. It passes because the correct answer not only has the most human characters, but the most characters total of any species

The correct answer should be required to include the WHERE statement below:

def select_series_title_with_most_human_characters
  "SELECT series.title 
  FROM series
  JOIN characters
  ON series.id = characters.series_id
  WHERE characters.species = 'human'
  GROUP BY series.title
  ORDER BY SUM(characters.species) DESC
  LIMIT 1"
end

**Comment by AnnJohn** [comment] 2016-04-25 18:26
hey @aturkewi were you planning on working on this? not a problem either way, but just wanted to know since i can reassign

**Comment by aturkewi** [comment] 2016-04-25 21:31
Yeah! Planning on working on this when I get a chance. Let me know if you need it done ASAP or anything @AnnJohn otherwise I'll try and get to it in the next week or so. Seems low priority because you can get through the lab, it's just not a very robust test :/

**Comment by AnnJohn** [comment] 2016-04-26 19:25
next week or so is great. thanks!

**Comment by maxwellbenton** [comment] 2019-08-02 22:01
Hi @snlamm,

Thank you for opening this issue. We've updated this lesson recently and have confirmed that the tests have been updated to require the use of `WHERE characters.species = 'human'` in this solution, which should resolve this issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Closed by maxwellbenton** 2019-08-02 22:01 UTC
Labels: test
